[package]
authors = ["Alex Yuhimenko <alexanderyuhimenko@gmail.com>"]
edition = "2021"
name = "mee_oidc"
version = "0.1.0"

[lib]
doc = false

[dependencies]
# mee_ds_sqlite = { path = "../mee_ds_sqlite" }

lazy_static = "1"
thiserror = "1"

[dev-dependencies]
actix-rt = "*"
